### PR TITLE
Add RTD site, Sphinx configuration

### LINKED ISSUE #1: Code fence labels work in  VS Code Preview but not Sphinx
I note you are using code fence labels of the form ` ```mermaid ` rather than the MyST/ `sphinxcontrib.mermaid` parsed convention ```{mermaid}` (which derives from the rst `.. mermaid::` form).

This forces folk into a position of having to use a different convention in a previewing editor to the form may be required when rendering the same document into a  static "published" form.

### LINKED ISSUE #5: Add Readthedocs
I've started the process for https://readthedocs.org/projects/markdown-it-mermaid/

It looks like it needs an _Owner_ to finish the setup:

https://readthedocs.org/dashboard/markdown-it-mermaid/integrations/

### PR DESCRIPTION
**Pull request by bollwyvl**
This adds a site that RTD can build. Here's the PR build:

https://markdown-it-mermaid--6.org.readthedocs.build/en/6/

## References
- fixes #5
- fixes #1

## Changes
- [x] adds config for readthedocs
- [x] add sphinx setup
- [x] update `www` to not do bootstrap stuff, add codemirror
- [x] bump version
- [x] add CHANGELOG
- [x] add installation instructions
- [x] add simple usage examples
- [x] run prettier on things
- [x] accept myst-style `{mermaid}` 

## Screens

Screenshot from 2022-09-17 17-39-53

### CODE REVIEW

**Comment by agoose77** [comment]
LGTM, thanks @bollwyvl  :)

**Comment by bollwyvl** [comment]
Dropped a few more things in (like prettier) as i had accidently committed with some autoformatting... figured might as well do it for real.

**Comment by agoose77** [comment]
Do we need `myst-nb` or can we use the subdependency `myst-parser`?

**Comment by bollwyvl** [comment]
Yeah, that works fine. Had no effect on the bottom line (169s either way) but fewer opinions always better.

**Comment by agoose77** [comment]
Fab, this is a big improvement.

**Pull request merged**
